language: node_js
node_js:
- node
before_install:
- cd app
after_script:
- cat ./coverage/lcov.info | coveralls
script: npm run test
env:
  global:
  - secure: SyBSaBDW78LCZKfGxXPOmx/fKXFAGYtJpQpGaT5g9zY3EFYSy9dLhaU15Bo71sKzwUbRQXVGwaqLxo/xrHxw2aKSIwkeGUlanwgP2CTBNOKCrtNiyYNJ4rlBSUK2xr3bC5muSmhfhw2B/V6uZwmAeQ8HhdUtLAvAQhK5xMgMNh9vupA9cRr8k24DQ3BwfvYx0p85tVcTjCwBXW0nBzmFDQQAdcwonncyEQOuEzVes00u4N8hQkzJF0vkU/sIB7E/qRGjIpMooFi/Gkb0ae56EQtmZ7hC4Dw46Gr6dtWwUiu3Cp2InCGpccJTTMCAfCGAoPElTRE20o4Fm5R7v0tO/G4aUayrbNuuGcHZ9wNmfD+YQ3wlWLeFSmseXTOINY8pFSzgJoPG3G8fbLgZLS+mWDPy0ZxJHNOMGqwFayM14/CHFW+m7k01GRGxDv7MedJmRbq4S6JeahZG/MGA54mZpvwVNcZxZmu7jO1eIK6mDFBAI4cDImMwEFmpjOVrec9pNb9i/87WQ0r5bZscpdniEqEWSqgY+Hk9WX06uhl21lQKjN9r1+J24oXjBL9C2BJXSQdAZGGAS0/lP2dK/uPHc6ukJsaSWyN4nWM1eLD5FeO5azezPZkc1BOl1FcL4hq6ofXggkUtibM9Xbwe0MXyU3uZ9+dGBWvN2I+6Wjg3Dpo=
  - secure: GUWMTblfzSZ0nBHXi8cTjxgCUKfh0dvcWcdGrWV5AK8r9gsEas7g6ihdITaFbZ3+5FNU98Oh+5mH5gLHevsCSSLDdv88+sQnn/aO+WsYc2NYayjXnb+GPLYr7snIWzneIC8/XafpwZBVd/6AArFGmimbrQBADTe7sC4fe19Hf3Y6EHEJlWrcbvVYdKTmoe9qTTl/t+eGcL2RpfodoY9hy9Tia6RH0OdZ/A0Fm7ODS9tLXCDYfP66yv4Kia+MS0tMta3SsPhWzJkisUZuP1uwKBtF/S9Vh4almQKIuIGHjxWqgbldxg8bgaZ9wr5ZLKv9gUXJlCZvlnwwknCLT+UblXtyCHG7NFaQ+EuCFGEX5SfpK/8I4ge1Toyn/5ZYKIyKW7DQjkks1BCPftzv7n5d1YkQEJ5k4iw5tRTx8uT9RQc/IQRnwd2hO6H4k1Cp6st8ErNr2yTOyIDeIuY5BXk1LDeuUFydckQnkfFRW+At07UiS7L5KSRftzvvO05cYR1XA/WgdaYP94qEpxvAOOn6pVYoNKld3yw+J9GrRghMxOrUIPKYT2SpIepP3B00aDFuVxGLdz2+S0f9bZ5DlVIiJr+vQLWIMC7+1mBQ/qp1cPx6NzkHuuOUVx71gV5lMAYVibCp39Er2a7ubGS3tF+WZwc59ELk4OVx0M7fB1P4+WI=
