/**
 * @jest-environment jsdom
 */

/* eslint-disable eslint-comments/disable-enable-pair */
/* eslint-disable @typescript-eslint/no-unsafe-return */
/* eslint-disable jest/valid-expect-in-promise */
/* eslint-disable no-magic-numbers */
import Manager from "@/views/Manager.vue";
import { mount } from "@vue/test-utils";
import ElementPlus from "element-plus";
import "element-plus/lib/theme-chalk/index.css";
import "isomorphic-fetch";
import nock from "nock";
import { OAUTH_API } from "../../helper/fetchHelper/fetchHelper";

const getWrapper = () =>
	mount(Manager, {
		global: {
			plugins: [ElementPlus],
		},
	});
/*
process.on("unhandledRejection", (error, promise) => {
	console.log("!!!!!!!!!!!!!!!!");
	console.log(promise);
	console.log(error);
}); */

// todo nock doc Memory issues with Jest
describe("Home.vue", () => {
	beforeAll(() => {
		/*	process.on("unhandledRejection", (error, promise) => {
			console.log("*****************");
			console.log(promise);
			console.log(error);
		}); */
		jest.resetAllMocks();
		nock(OAUTH_API)
			.get("/api/v1/me")
			.reply(200, { a: "a", name: "bla", is_gold: false })
			.get(/\/user\/\w+\/saved.+$/)
			.reply(200, {
				kind: "Listing",
				data: {
					modhash: null,
					dist: 100,
					children: [
						{
							text: "",
							kind: "t3",
							data: {
								approved_at_utc: null,
								subreddit: "Unity3D",
								selftext: "",
								author_fullname: "t2_8tsfdgm4",
								saved: true,
								mod_reason_title: null,
								gilded: 0,
								clicked: false,
								is_gallery: true,
								title: "Ancient Fantasy Village",
								link_flair_richtext: [
									{
										e: "text",
										t: "Show-Off",
									},
								],
								subreddit_name_prefixed: "r/Unity3D",
								hidden: false,
								pwls: null,
								link_flair_css_class: "",
								downs: 0,
								thumbnail_height: 140,
								top_awarded_type: null,
								hide_score: false,
								media_metadata: {
									ywy9xkuxc4161: {
										status: "valid",
										e: "Image",
										m: "image/jpg",
										p: [
											{
												y: 108,
												x: 108,
												u:
													"https://preview.redd.it/ywy9xkuxc4161.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=c17ab5652adb94f3339c29b51c9dc244a95dccb0",
											},
											{
												y: 216,
												x: 216,
												u:
													"https://preview.redd.it/ywy9xkuxc4161.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=0f0fdd75393bf8f31c2af90264198ad493ae4d84",
											},
											{
												y: 320,
												x: 320,
												u:
													"https://preview.redd.it/ywy9xkuxc4161.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=d57cea5dbfb88609bc61080d1267e1f9ffb16083",
											},
											{
												y: 640,
												x: 640,
												u:
													"https://preview.redd.it/ywy9xkuxc4161.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=79c3bc3da7b442e73b646a9ae7341de9772f0956",
											},
											{
												y: 960,
												x: 960,
												u:
													"https://preview.redd.it/ywy9xkuxc4161.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=c75776898dba9cb84beaed82143d6e150d720356",
											},
											{
												y: 1080,
												x: 1080,
												u:
													"https://preview.redd.it/ywy9xkuxc4161.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=d544e3e9323dd36a3318c8779c96fb2da36e678a",
											},
										],
										s: {
											y: 1080,
											x: 1080,
											u:
												"https://preview.redd.it/ywy9xkuxc4161.jpg?width=1080&amp;format=pjpg&amp;auto=webp&amp;s=9363c571d31a9ef60dce6c231f09688d38916059",
										},
										id: "ywy9xkuxc4161",
									},
									e581qnuxc4161: {
										status: "valid",
										e: "Image",
										m: "image/jpg",
										p: [
											{
												y: 108,
												x: 108,
												u:
													"https://preview.redd.it/e581qnuxc4161.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=d0cbcf3b7a806fb48041d7d614af25cc3b685ae7",
											},
											{
												y: 216,
												x: 216,
												u:
													"https://preview.redd.it/e581qnuxc4161.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=010683e6d55037b2fec41b4c3233c517b1049d16",
											},
											{
												y: 320,
												x: 320,
												u:
													"https://preview.redd.it/e581qnuxc4161.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=ef6d7904821754e8fce4cf80138f3e05b28e4c82",
											},
											{
												y: 640,
												x: 640,
												u:
													"https://preview.redd.it/e581qnuxc4161.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=40f8e2bc14a8d16a246482c95a0c0eafca17f6f5",
											},
											{
												y: 960,
												x: 960,
												u:
													"https://preview.redd.it/e581qnuxc4161.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=e63642c97f9d4bedd6696329829cc84e38b87486",
											},
											{
												y: 1080,
												x: 1080,
												u:
													"https://preview.redd.it/e581qnuxc4161.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=136987251043e90fb01615cb8a6945029b634e19",
											},
										],
										s: {
											y: 1080,
											x: 1080,
											u:
												"https://preview.redd.it/e581qnuxc4161.jpg?width=1080&amp;format=pjpg&amp;auto=webp&amp;s=dc5cbcbffcf5abc24ad258f447fc84f2eea36a6a",
										},
										id: "e581qnuxc4161",
									},
								},
								name: "t3_jzyih0",
								quarantine: false,
								link_flair_text_color: "light",
								upvote_ratio: 0.97,
								author_flair_background_color: null,
								subreddit_type: "public",
								ups: 27,
								total_awards_received: 0,
								media_embed: {},
								thumbnail_width: 140,
								author_flair_template_id: null,
								is_original_content: false,
								user_reports: [],
								secure_media: null,
								is_reddit_media_domain: false,
								is_meta: false,
								category: null,
								secure_media_embed: {},
								gallery_data: {
									items: [
										{
											caption: "Day",
											media_id: "ywy9xkuxc4161",
											id: 14194001,
										},
										{
											caption: "Night",
											media_id: "e581qnuxc4161",
											id: 14194002,
										},
									],
								},
								link_flair_text: "Show-Off",
								can_mod_post: false,
								score: 27,
								approved_by: null,
								author_premium: false,
								thumbnail:
									"https://a.thumbs.redditmedia.com/G-yjP0dRuToDyqN-ICgXZk5H7CWjVbPyijM3XCcFbV8.jpg",
								edited: false,
								author_flair_css_class: null,
								author_flair_richtext: [],
								gildings: {},
								content_categories: null,
								is_self: false,
								mod_note: null,
								created: 1606222520,
								link_flair_type: "richtext",
								wls: null,
								removed_by_category: null,
								banned_by: null,
								author_flair_type: "text",
								domain: "reddit.com",
								allow_live_comments: false,
								selftext_html: null,
								likes: null,
								suggested_sort: null,
								banned_at_utc: null,
								url_overridden_by_dest: "https://www.reddit.com/gallery/jzyih0",
								view_count: null,
								archived: false,
								no_follow: false,
								is_crosspostable: true,
								pinned: false,
								over_18: false,
								all_awardings: [],
								awarders: [],
								media_only: false,
								link_flair_template_id: "14ada858-4aed-11e5-9227-0e5e20c89e15",
								can_gild: true,
								spoiler: false,
								locked: false,
								author_flair_text: null,
								treatment_tags: [],
								visited: false,
								removed_by: null,
								num_reports: null,
								distinguished: null,
								subreddit_id: "t5_2qwj8",
								mod_reason_by: null,
								removal_reason: null,
								link_flair_background_color: "#0aa18f",
								id: "jzyih0",
								is_robot_indexable: true,
								report_reasons: null,
								author: "renderisland",
								discussion_type: null,
								num_comments: 2,
								send_replies: true,
								whitelist_status: null,
								contest_mode: false,
								mod_reports: [],
								author_patreon_flair: false,
								author_flair_text_color: null,
								permalink:
									"/r/Unity3D/comments/jzyih0/ancient_fantasy_village/",
								parent_whitelist_status: null,
								stickied: false,
								url: "https://www.reddit.com/gallery/jzyih0",
								subreddit_subscribers: 226820,
								created_utc: 1606193720,
								num_crossposts: 0,
								media: null,
								is_video: false,
							},
							author: "renderisland",
							id: "jzyih0",
							fullname: "t3_jzyih0",
							subreddit: "Unity3D",
							subredditID: "t5_2qwj8",
							redditLink: "/r/Unity3D/comments/jzyih0/ancient_fantasy_village/",
							title: "Ancient Fantasy Village",
							url: "https://www.reddit.com/gallery/jzyih0",
							isVideo: false,
							media: null,
							numComment: 2,
							isSelf: false,
							thumbnail:
								"https://a.thumbs.redditmedia.com/G-yjP0dRuToDyqN-ICgXZk5H7CWjVbPyijM3XCcFbV8.jpg",
							urlOverriddenByDest: "https://www.reddit.com/gallery/jzyih0",
							isGallery: true,
							type: "unknown",
							mediaURL: "",
						},
						{
							text:
								"Bro that show is gold. Only love is war gets more laughs out of me as far as anime goes",
							kind: "t1",
							data: {
								total_awards_received: 0,
								approved_at_utc: null,
								comment_type: null,
								awarders: [],
								mod_reason_by: null,
								banned_by: null,
								author_flair_type: "text",
								removal_reason: null,
								link_id: "t3_glc9xj",
								author_flair_template_id: null,
								likes: null,
								replies: "",
								user_reports: [],
								saved: true,
								id: "fqxl1kz",
								banned_at_utc: null,
								mod_reason_title: null,
								gilded: 0,
								archived: true,
								no_follow: false,
								author: "BumLeeJon",
								num_comments: 248,
								edited: false,
								can_mod_post: false,
								created_utc: 1589733946,
								send_replies: true,
								parent_id: "t1_fqxklj9",
								score: 15,
								author_fullname: "t2_187yx4j3",
								over_18: false,
								treatment_tags: [],
								approved_by: null,
								mod_note: null,
								all_awardings: [],
								subreddit_id: "t5_2vnbs",
								body:
									"Bro that show is gold. Only love is war gets more laughs out of me as far as anime goes",
								link_title: "The True Trickster",
								author_flair_css_class: null,
								name: "t1_fqxl1kz",
								author_patreon_flair: false,
								downs: 0,
								author_flair_richtext: [],
								is_submitter: false,
								body_html:
									'&lt;div class="md"&gt;&lt;p&gt;Bro that show is gold. Only love is war gets more laughs out of me as far as anime goes&lt;/p&gt;\n&lt;/div&gt;',
								gildings: {},
								collapsed_reason: null,
								distinguished: null,
								associated_award: null,
								stickied: false,
								author_premium: false,
								can_gild: true,
								top_awarded_type: null,
								author_flair_text_color: null,
								score_hidden: false,
								permalink:
									"/r/Persona5/comments/glc9xj/the_true_trickster/fqxl1kz/",
								num_reports: null,
								link_permalink:
									"https://www.reddit.com/r/Persona5/comments/glc9xj/the_true_trickster/",
								report_reasons: null,
								link_author: "Pokepingui",
								subreddit: "Persona5",
								author_flair_text: null,
								link_url: "https://i.redd.it/8oy6w4pmiaz41.jpg",
								created: 1589762746,
								collapsed: false,
								subreddit_name_prefixed: "r/Persona5",
								controversiality: 0,
								locked: false,
								author_flair_background_color: null,
								collapsed_because_crowd_control: null,
								mod_reports: [],
								quarantine: false,
								subreddit_type: "public",
								ups: 15,
							},
							author: "BumLeeJon",
							id: "fqxl1kz",
							fullname: "t1_fqxl1kz",
							subreddit: "Persona5",
							subredditID: "t5_2vnbs",
							redditLink:
								"/r/Persona5/comments/glc9xj/the_true_trickster/fqxl1kz/",
							linkAuthor: "Pokepingui",
							linkId: "t3_glc9xj",
							parentID: "t1_fqxklj9",
							linkTitle: "The True Trickster",
							linkPermalink:
								"https://www.reddit.com/r/Persona5/comments/glc9xj/the_true_trickster/",
							linkURL: "https://i.redd.it/8oy6w4pmiaz41.jpg",
							type: "comment",
						},
						{
							text: "",
							kind: "t3",
							data: {
								approved_at_utc: null,
								subreddit: "UXDesign",
								selftext: "",
								author_fullname: "t2_5jk4meja",
								saved: true,
								mod_reason_title: null,
								gilded: 0,
								clicked: false,
								title: "21st Century Design by Don Norman",
								link_flair_richtext: [],
								subreddit_name_prefixed: "r/UXDesign",
								hidden: false,
								pwls: 6,
								link_flair_css_class: null,
								downs: 0,
								thumbnail_height: 105,
								top_awarded_type: null,
								hide_score: false,
								name: "t3_gjm0m7",
								quarantine: false,
								link_flair_text_color: "dark",
								upvote_ratio: 0.97,
								author_flair_background_color: null,
								subreddit_type: "public",
								ups: 61,
								total_awards_received: 0,
								media_embed: {
									content:
										'&lt;iframe width="600" height="338" src="https://www.youtube.com/embed/7FJNsqoC4tI?feature=oembed&amp;enablejsapi=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen&gt;&lt;/iframe&gt;',
									width: 600,
									scrolling: false,
									height: 338,
								},
								thumbnail_width: 140,
								author_flair_template_id: null,
								is_original_content: false,
								user_reports: [],
								secure_media: {
									oembed: {
										provider_url: "https://www.youtube.com/",
										title: "21st Century Design",
										html:
											'&lt;iframe width="600" height="338" src="https://www.youtube.com/embed/7FJNsqoC4tI?feature=oembed&amp;enablejsapi=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen&gt;&lt;/iframe&gt;',
										thumbnail_width: 480,
										height: 338,
										width: 600,
										version: "1.0",
										author_name: "NNgroup",
										provider_name: "YouTube",
										thumbnail_url:
											"https://i.ytimg.com/vi/7FJNsqoC4tI/hqdefault.jpg",
										type: "video",
										thumbnail_height: 360,
										author_url: "https://www.youtube.com/user/NNgroup",
									},
									type: "youtube.com",
								},
								is_reddit_media_domain: false,
								is_meta: false,
								category: null,
								secure_media_embed: {
									content:
										'&lt;iframe width="600" height="338" src="https://www.youtube.com/embed/7FJNsqoC4tI?feature=oembed&amp;enablejsapi=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen&gt;&lt;/iframe&gt;',
									width: 600,
									scrolling: false,
									media_domain_url:
										"https://www.redditmedia.com/mediaembed/gjm0m7",
									height: 338,
								},
								link_flair_text: null,
								can_mod_post: false,
								score: 61,
								approved_by: null,
								author_premium: false,
								thumbnail:
									"https://b.thumbs.redditmedia.com/KKlTdZA5fvBrC_C135QC70qLDb8niLz_0qWtkK_SIOE.jpg",
								edited: false,
								author_flair_css_class: null,
								author_flair_richtext: [],
								gildings: {},
								post_hint: "rich:video",
								content_categories: null,
								is_self: false,
								mod_note: null,
								created: 1589490531,
								link_flair_type: "text",
								wls: 6,
								removed_by_category: null,
								banned_by: null,
								author_flair_type: "text",
								domain: "youtu.be",
								allow_live_comments: false,
								selftext_html: null,
								likes: null,
								suggested_sort: null,
								banned_at_utc: null,
								url_overridden_by_dest: "https://youtu.be/7FJNsqoC4tI",
								view_count: null,
								archived: true,
								no_follow: false,
								is_crosspostable: true,
								pinned: false,
								over_18: false,
								preview: {
									images: [
										{
											source: {
												url:
													"https://external-preview.redd.it/iEbG7k-TMpDUlpj5RDzFOjDHihnIrPpGKEwolxt_kTY.jpg?auto=webp&amp;s=89dbfbe3bcb0a0b0a54ce355b92ebc9a848e2079",
												width: 480,
												height: 360,
											},
											resolutions: [
												{
													url:
														"https://external-preview.redd.it/iEbG7k-TMpDUlpj5RDzFOjDHihnIrPpGKEwolxt_kTY.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=676e5ff5879c1cd7eeca676cd687cf905b8abf97",
													width: 108,
													height: 81,
												},
												{
													url:
														"https://external-preview.redd.it/iEbG7k-TMpDUlpj5RDzFOjDHihnIrPpGKEwolxt_kTY.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=1259d319c434168a0b8db7033ecac80bee5003fa",
													width: 216,
													height: 162,
												},
												{
													url:
														"https://external-preview.redd.it/iEbG7k-TMpDUlpj5RDzFOjDHihnIrPpGKEwolxt_kTY.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=d91233a58b5924ec9cfeec89a67ff64610c26a7a",
													width: 320,
													height: 240,
												},
											],
											variants: {},
											id: "-zeLgUdUYZchSAwW2HpYqcj7iULtHJoVLr3D4BjaW9g",
										},
									],
									enabled: false,
								},
								all_awardings: [],
								awarders: [],
								media_only: false,
								can_gild: true,
								spoiler: false,
								locked: false,
								author_flair_text: null,
								treatment_tags: [],
								visited: false,
								removed_by: null,
								num_reports: null,
								distinguished: null,
								subreddit_id: "t5_2u66g",
								mod_reason_by: null,
								removal_reason: null,
								link_flair_background_color: "",
								id: "gjm0m7",
								is_robot_indexable: true,
								report_reasons: null,
								author: "thedesignninja",
								discussion_type: null,
								num_comments: 13,
								send_replies: true,
								whitelist_status: "all_ads",
								contest_mode: false,
								mod_reports: [],
								author_patreon_flair: false,
								author_flair_text_color: null,
								permalink:
									"/r/UXDesign/comments/gjm0m7/21st_century_design_by_don_norman/",
								parent_whitelist_status: "all_ads",
								stickied: false,
								url: "https://youtu.be/7FJNsqoC4tI",
								subreddit_subscribers: 40613,
								created_utc: 1589461731,
								num_crossposts: 1,
								media: {
									oembed: {
										provider_url: "https://www.youtube.com/",
										title: "21st Century Design",
										html:
											'&lt;iframe width="600" height="338" src="https://www.youtube.com/embed/7FJNsqoC4tI?feature=oembed&amp;enablejsapi=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen&gt;&lt;/iframe&gt;',
										thumbnail_width: 480,
										height: 338,
										width: 600,
										version: "1.0",
										author_name: "NNgroup",
										provider_name: "YouTube",
										thumbnail_url:
											"https://i.ytimg.com/vi/7FJNsqoC4tI/hqdefault.jpg",
										type: "video",
										thumbnail_height: 360,
										author_url: "https://www.youtube.com/user/NNgroup",
									},
									type: "youtube.com",
								},
								is_video: false,
							},
							author: "thedesignninja",
							id: "gjm0m7",
							fullname: "t3_gjm0m7",
							subreddit: "UXDesign",
							subredditID: "t5_2u66g",
							redditLink:
								"/r/UXDesign/comments/gjm0m7/21st_century_design_by_don_norman/",
							title: "21st Century Design by Don Norman",
							url: "https://youtu.be/7FJNsqoC4tI",
							isVideo: false,
							media: {
								oembed: {
									provider_url: "https://www.youtube.com/",
									title: "21st Century Design",
									html:
										'&lt;iframe width="600" height="338" src="https://www.youtube.com/embed/7FJNsqoC4tI?feature=oembed&amp;enablejsapi=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen&gt;&lt;/iframe&gt;',
									thumbnail_width: 480,
									height: 338,
									width: 600,
									version: "1.0",
									author_name: "NNgroup",
									provider_name: "YouTube",
									thumbnail_url:
										"https://i.ytimg.com/vi/7FJNsqoC4tI/hqdefault.jpg",
									type: "video",
									thumbnail_height: 360,
									author_url: "https://www.youtube.com/user/NNgroup",
								},
								type: "youtube.com",
							},
							numComment: 13,
							postHint: "rich:video",
							isSelf: false,
							thumbnail:
								"https://b.thumbs.redditmedia.com/KKlTdZA5fvBrC_C135QC70qLDb8niLz_0qWtkK_SIOE.jpg",
							urlOverriddenByDest: "https://youtu.be/7FJNsqoC4tI",
							type: "video",
							mediaURL: "",
						},
						{
							text:
								"Hello tout le monde,\n\nJ'ouvre cette semaine un PEA et un CTO chez Binck. A terme j'aimerais investir dans des actifs/actions Americaines et Europeennes. \n\nPour le moment je suis entrain de lire Investisseurs Intelligent, mais il n'est pas simple. Auriez vous d'autres ressosurces a me suggerer?\n\nBonne journee!",
							kind: "t3",
							data: {
								approved_at_utc: null,
								subreddit: "vosfinances",
								selftext:
									"Hello tout le monde,\n\nJ'ouvre cette semaine un PEA et un CTO chez Binck. A terme j'aimerais investir dans des actifs/actions Americaines et Europeennes. \n\nPour le moment je suis entrain de lire Investisseurs Intelligent, mais il n'est pas simple. Auriez vous d'autres ressosurces a me suggerer?\n\nBonne journee!",
								author_fullname: "t2_5392jtn",
								saved: true,
								mod_reason_title: null,
								gilded: 0,
								clicked: false,
								title: "PEA - CTO",
								link_flair_richtext: [
									{
										e: "text",
										t: "Investissements",
									},
								],
								subreddit_name_prefixed: "r/vosfinances",
								hidden: false,
								pwls: 7,
								link_flair_css_class: "",
								downs: 0,
								thumbnail_height: null,
								top_awarded_type: null,
								hide_score: false,
								name: "t3_errjwg",
								quarantine: false,
								link_flair_text_color: "dark",
								upvote_ratio: 0.86,
								author_flair_background_color: null,
								subreddit_type: "public",
								ups: 5,
								total_awards_received: 0,
								media_embed: {},
								thumbnail_width: null,
								author_flair_template_id: null,
								is_original_content: false,
								user_reports: [],
								secure_media: null,
								is_reddit_media_domain: false,
								is_meta: false,
								category: null,
								secure_media_embed: {},
								link_flair_text: "Investissements",
								can_mod_post: false,
								score: 5,
								approved_by: null,
								author_premium: false,
								thumbnail: "self",
								edited: false,
								author_flair_css_class: null,
								author_flair_richtext: [],
								gildings: {},
								content_categories: null,
								is_self: true,
								mod_note: null,
								created: 1579622344,
								link_flair_type: "richtext",
								wls: 7,
								removed_by_category: null,
								banned_by: null,
								author_flair_type: "text",
								domain: "self.vosfinances",
								allow_live_comments: false,
								selftext_html:
									'&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;Hello tout le monde,&lt;/p&gt;\n\n&lt;p&gt;J&amp;#39;ouvre cette semaine un PEA et un CTO chez Binck. A terme j&amp;#39;aimerais investir dans des actifs/actions Americaines et Europeennes. &lt;/p&gt;\n\n&lt;p&gt;Pour le moment je suis entrain de lire Investisseurs Intelligent, mais il n&amp;#39;est pas simple. Auriez vous d&amp;#39;autres ressosurces a me suggerer?&lt;/p&gt;\n\n&lt;p&gt;Bonne journee!&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
								likes: null,
								suggested_sort: null,
								banned_at_utc: null,
								view_count: null,
								archived: true,
								no_follow: false,
								is_crosspostable: true,
								pinned: false,
								over_18: false,
								all_awardings: [],
								awarders: [],
								media_only: false,
								link_flair_template_id: "4373035e-4977-11e9-aab6-0ee12f3f3260",
								can_gild: true,
								spoiler: false,
								locked: false,
								author_flair_text: null,
								treatment_tags: [],
								visited: false,
								removed_by: null,
								num_reports: null,
								distinguished: null,
								subreddit_id: "t5_37aoh",
								mod_reason_by: null,
								removal_reason: null,
								link_flair_background_color: "#9ee7ab",
								id: "errjwg",
								is_robot_indexable: true,
								report_reasons: null,
								author: "knandraina",
								discussion_type: null,
								num_comments: 15,
								send_replies: true,
								whitelist_status: "some_ads",
								contest_mode: false,
								mod_reports: [],
								author_patreon_flair: false,
								author_flair_text_color: null,
								permalink: "/r/vosfinances/comments/errjwg/pea_cto/",
								parent_whitelist_status: "some_ads",
								stickied: false,
								url:
									"https://www.reddit.com/r/vosfinances/comments/errjwg/pea_cto/",
								subreddit_subscribers: 31249,
								created_utc: 1579593544,
								num_crossposts: 0,
								media: null,
								is_video: false,
							},
							author: "knandraina",
							id: "errjwg",
							fullname: "t3_errjwg",
							subreddit: "vosfinances",
							subredditID: "t5_37aoh",
							redditLink: "/r/vosfinances/comments/errjwg/pea_cto/",
							title: "PEA - CTO",
							url:
								"https://www.reddit.com/r/vosfinances/comments/errjwg/pea_cto/",
							isVideo: false,
							media: null,
							numComment: 15,
							isSelf: true,
							thumbnail: "self",
							type: "text",
							mediaURL: "",
						},
						{
							text:
								"Hey everyone,\n\nWe have curated a collection of links for User Flows. I think they might be helpful for someone trying to learn UX and UI design. I really found them helpful, they come handy in a lot of ways. There are 3 main benefits of using user flows for me;\n\n1. They are easy to sketch and help you to see big picture. So, they help you to see bigger picture in less time.\n2. When used properly helps you to communicate transparently between team about the product. For instance, we are team of 2 and user flows help me to communicate with my technical partner. This communication prevent any unexpected surprises at the end of each product spec. because this is a great tool to show and narrate the expected architecture and the logic of the product.\n3. Help you to avoid any potential design pitfall. If you use properly, as I said it will help you to understand logic and also the view of users, so you will be less likely to create a design pitfall on your work.\n\nLet me know, do you agree or disagree with me.\n\nHere's the list;\n\n1. [https://uxdesign.cc/the-biggest-wtf-in-design-right-now-87139f367d66](https://uxdesign.cc/the-biggest-wtf-in-design-right-now-87139f367d66)\n2. [https://uxdesign.cc/when-to-use-user-flows-guide-8b26ca9aa36a](https://uxdesign.cc/when-to-use-user-flows-guide-8b26ca9aa36a)\n3. [https://uxplanet.org/ux-glossary-task-flows-user-flows-flowcharts-and-some-new-ish-stuff-2321044d837d](https://uxplanet.org/ux-glossary-task-flows-user-flows-flowcharts-and-some-new-ish-stuff-2321044d837d)\n4. [https://uxmovement.com/wireframes/site-flows-vs-user-flows-when-to-use-which/](https://uxmovement.com/wireframes/site-flows-vs-user-flows-when-to-use-which/)\n5. [https://uxplanet.org/an-introduction-to-interaction-flows-a4f783402529](https://uxplanet.org/an-introduction-to-interaction-flows-a4f783402529)\n6. [https://youtu.be/TIV1y11xz7k](https://youtu.be/TIV1y11xz7k)\n7. [https://signalvnoise.com/posts/1926-a-shorthand-for-designing-ui-flows](https://signalvnoise.com/posts/1926-a-shorthand-for-designing-ui-flows)\n8. [https://www.youtube.com/watch?v=yrtph9owtpe](https://www.youtube.com/watch?v=yrtph9owtpe)\n9. [https://careerfoundry.com/en/blog/ux-design/how-to-create-a-user-flow/](https://careerfoundry.com/en/blog/ux-design/how-to-create-a-user-flow/)\n10. [https://blog.prototypr.io/ux-design-101-thinking-in-user-flows-8b571661866](https://blog.prototypr.io/ux-design-101-thinking-in-user-flows-8b571661866)\n\nHave to put little disclaimer; We have curated this list for [**Jooseph**](https://jooseph.com/?utm_source=reddit.com&amp;utm_medium=referral&amp;utm_campaign=11.05&amp;utm_term=r%2userexperience&amp;utm_content=Landing%20Page) which is a place where you can follow curated collections of links for a subject. We have couple of other collections about UX and UI over-there if you want to check.\n\nI hope it helps,",
							kind: "t3",
							data: {
								approved_at_utc: null,
								subreddit: "UXDesign",
								selftext:
									"Hey everyone,\n\nWe have curated a collection of links for User Flows. I think they might be helpful for someone trying to learn UX and UI design. I really found them helpful, they come handy in a lot of ways. There are 3 main benefits of using user flows for me;\n\n1. They are easy to sketch and help you to see big picture. So, they help you to see bigger picture in less time.\n2. When used properly helps you to communicate transparently between team about the product. For instance, we are team of 2 and user flows help me to communicate with my technical partner. This communication prevent any unexpected surprises at the end of each product spec. because this is a great tool to show and narrate the expected architecture and the logic of the product.\n3. Help you to avoid any potential design pitfall. If you use properly, as I said it will help you to understand logic and also the view of users, so you will be less likely to create a design pitfall on your work.\n\nLet me know, do you agree or disagree with me.\n\nHere's the list;\n\n1. [https://uxdesign.cc/the-biggest-wtf-in-design-right-now-87139f367d66](https://uxdesign.cc/the-biggest-wtf-in-design-right-now-87139f367d66)\n2. [https://uxdesign.cc/when-to-use-user-flows-guide-8b26ca9aa36a](https://uxdesign.cc/when-to-use-user-flows-guide-8b26ca9aa36a)\n3. [https://uxplanet.org/ux-glossary-task-flows-user-flows-flowcharts-and-some-new-ish-stuff-2321044d837d](https://uxplanet.org/ux-glossary-task-flows-user-flows-flowcharts-and-some-new-ish-stuff-2321044d837d)\n4. [https://uxmovement.com/wireframes/site-flows-vs-user-flows-when-to-use-which/](https://uxmovement.com/wireframes/site-flows-vs-user-flows-when-to-use-which/)\n5. [https://uxplanet.org/an-introduction-to-interaction-flows-a4f783402529](https://uxplanet.org/an-introduction-to-interaction-flows-a4f783402529)\n6. [https://youtu.be/TIV1y11xz7k](https://youtu.be/TIV1y11xz7k)\n7. [https://signalvnoise.com/posts/1926-a-shorthand-for-designing-ui-flows](https://signalvnoise.com/posts/1926-a-shorthand-for-designing-ui-flows)\n8. [https://www.youtube.com/watch?v=yrtph9owtpe](https://www.youtube.com/watch?v=yrtph9owtpe)\n9. [https://careerfoundry.com/en/blog/ux-design/how-to-create-a-user-flow/](https://careerfoundry.com/en/blog/ux-design/how-to-create-a-user-flow/)\n10. [https://blog.prototypr.io/ux-design-101-thinking-in-user-flows-8b571661866](https://blog.prototypr.io/ux-design-101-thinking-in-user-flows-8b571661866)\n\nHave to put little disclaimer; We have curated this list for [**Jooseph**](https://jooseph.com/?utm_source=reddit.com&amp;utm_medium=referral&amp;utm_campaign=11.05&amp;utm_term=r%2userexperience&amp;utm_content=Landing%20Page) which is a place where you can follow curated collections of links for a subject. We have couple of other collections about UX and UI over-there if you want to check.\n\nI hope it helps,",
								author_fullname: "t2_5mtce84c",
								saved: true,
								mod_reason_title: null,
								gilded: 0,
								clicked: false,
								title: "We have curated a list of resources about User Flow",
								link_flair_richtext: [],
								subreddit_name_prefixed: "r/UXDesign",
								hidden: false,
								pwls: 6,
								link_flair_css_class: null,
								downs: 0,
								thumbnail_height: null,
								top_awarded_type: null,
								hide_score: false,
								name: "t3_ghpx8a",
								quarantine: false,
								link_flair_text_color: "dark",
								upvote_ratio: 0.86,
								author_flair_background_color: null,
								subreddit_type: "public",
								ups: 5,
								total_awards_received: 0,
								media_embed: {},
								thumbnail_width: null,
								author_flair_template_id: null,
								is_original_content: false,
								user_reports: [],
								secure_media: null,
								is_reddit_media_domain: false,
								is_meta: false,
								category: null,
								secure_media_embed: {},
								link_flair_text: null,
								can_mod_post: false,
								score: 5,
								approved_by: null,
								author_premium: false,
								thumbnail: "self",
								edited: false,
								author_flair_css_class: null,
								author_flair_richtext: [],
								gildings: {},
								post_hint: "self",
								content_categories: null,
								is_self: true,
								mod_note: null,
								created: 1589240476,
								link_flair_type: "text",
								wls: 6,
								removed_by_category: null,
								banned_by: null,
								author_flair_type: "text",
								domain: "self.UXDesign",
								allow_live_comments: false,
								selftext_html:
									'&lt;!-- SC_OFF --&gt;&lt;div class="md"&gt;&lt;p&gt;Hey everyone,&lt;/p&gt;\n\n&lt;p&gt;We have curated a collection of links for User Flows. I think they might be helpful for someone trying to learn UX and UI design. I really found them helpful, they come handy in a lot of ways. There are 3 main benefits of using user flows for me;&lt;/p&gt;\n\n&lt;ol&gt;\n&lt;li&gt;They are easy to sketch and help you to see big picture. So, they help you to see bigger picture in less time.&lt;/li&gt;\n&lt;li&gt;When used properly helps you to communicate transparently between team about the product. For instance, we are team of 2 and user flows help me to communicate with my technical partner. This communication prevent any unexpected surprises at the end of each product spec. because this is a great tool to show and narrate the expected architecture and the logic of the product.&lt;/li&gt;\n&lt;li&gt;Help you to avoid any potential design pitfall. If you use properly, as I said it will help you to understand logic and also the view of users, so you will be less likely to create a design pitfall on your work.&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;p&gt;Let me know, do you agree or disagree with me.&lt;/p&gt;\n\n&lt;p&gt;Here&amp;#39;s the list;&lt;/p&gt;\n\n&lt;ol&gt;\n&lt;li&gt;&lt;a href="https://uxdesign.cc/the-biggest-wtf-in-design-right-now-87139f367d66"&gt;https://uxdesign.cc/the-biggest-wtf-in-design-right-now-87139f367d66&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href="https://uxdesign.cc/when-to-use-user-flows-guide-8b26ca9aa36a"&gt;https://uxdesign.cc/when-to-use-user-flows-guide-8b26ca9aa36a&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href="https://uxplanet.org/ux-glossary-task-flows-user-flows-flowcharts-and-some-new-ish-stuff-2321044d837d"&gt;https://uxplanet.org/ux-glossary-task-flows-user-flows-flowcharts-and-some-new-ish-stuff-2321044d837d&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href="https://uxmovement.com/wireframes/site-flows-vs-user-flows-when-to-use-which/"&gt;https://uxmovement.com/wireframes/site-flows-vs-user-flows-when-to-use-which/&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href="https://uxplanet.org/an-introduction-to-interaction-flows-a4f783402529"&gt;https://uxplanet.org/an-introduction-to-interaction-flows-a4f783402529&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href="https://youtu.be/TIV1y11xz7k"&gt;https://youtu.be/TIV1y11xz7k&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href="https://signalvnoise.com/posts/1926-a-shorthand-for-designing-ui-flows"&gt;https://signalvnoise.com/posts/1926-a-shorthand-for-designing-ui-flows&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href="https://www.youtube.com/watch?v=yrtph9owtpe"&gt;https://www.youtube.com/watch?v=yrtph9owtpe&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href="https://careerfoundry.com/en/blog/ux-design/how-to-create-a-user-flow/"&gt;https://careerfoundry.com/en/blog/ux-design/how-to-create-a-user-flow/&lt;/a&gt;&lt;/li&gt;\n&lt;li&gt;&lt;a href="https://blog.prototypr.io/ux-design-101-thinking-in-user-flows-8b571661866"&gt;https://blog.prototypr.io/ux-design-101-thinking-in-user-flows-8b571661866&lt;/a&gt;&lt;/li&gt;\n&lt;/ol&gt;\n\n&lt;p&gt;Have to put little disclaimer; We have curated this list for &lt;a href="https://jooseph.com/?utm_source=reddit.com&amp;amp;utm_medium=referral&amp;amp;utm_campaign=11.05&amp;amp;utm_term=r%2userexperience&amp;amp;utm_content=Landing%20Page"&gt;&lt;strong&gt;Jooseph&lt;/strong&gt;&lt;/a&gt; which is a place where you can follow curated collections of links for a subject. We have couple of other collections about UX and UI over-there if you want to check.&lt;/p&gt;\n\n&lt;p&gt;I hope it helps,&lt;/p&gt;\n&lt;/div&gt;&lt;!-- SC_ON --&gt;',
								likes: null,
								suggested_sort: null,
								banned_at_utc: null,
								view_count: null,
								archived: true,
								no_follow: false,
								is_crosspostable: true,
								pinned: false,
								over_18: false,
								preview: {
									images: [
										{
											source: {
												url:
													"https://external-preview.redd.it/iRky1CEuLCKhbHUYbYxpIakVCX_5uvbh_2KLUvCKDXI.jpg?auto=webp&amp;s=5ebf257652d477829527dc98207b860a3ac6320a",
												width: 1032,
												height: 652,
											},
											resolutions: [
												{
													url:
														"https://external-preview.redd.it/iRky1CEuLCKhbHUYbYxpIakVCX_5uvbh_2KLUvCKDXI.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=e23342844ec957a36f8fb95f287d86002050b18f",
													width: 108,
													height: 68,
												},
												{
													url:
														"https://external-preview.redd.it/iRky1CEuLCKhbHUYbYxpIakVCX_5uvbh_2KLUvCKDXI.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=58249ee69e120275e612058f4a440754228714c4",
													width: 216,
													height: 136,
												},
												{
													url:
														"https://external-preview.redd.it/iRky1CEuLCKhbHUYbYxpIakVCX_5uvbh_2KLUvCKDXI.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=7fc3901672c9b425095f321e063e14aac05e31ff",
													width: 320,
													height: 202,
												},
												{
													url:
														"https://external-preview.redd.it/iRky1CEuLCKhbHUYbYxpIakVCX_5uvbh_2KLUvCKDXI.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=95a960a60a9868b35beec45a0a103db308dfedcb",
													width: 640,
													height: 404,
												},
												{
													url:
														"https://external-preview.redd.it/iRky1CEuLCKhbHUYbYxpIakVCX_5uvbh_2KLUvCKDXI.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=0aad50edd6a276eeeb5cce00b34ecbc3401cb370",
													width: 960,
													height: 606,
												},
											],
											variants: {},
											id: "_GP192gCpPtwzPq5XmaSKZbp8p1xWoySsscFd0Bz50g",
										},
									],
									enabled: false,
								},
								all_awardings: [],
								awarders: [],
								media_only: false,
								can_gild: true,
								spoiler: false,
								locked: false,
								author_flair_text: null,
								treatment_tags: [],
								visited: false,
								removed_by: null,
								num_reports: null,
								distinguished: null,
								subreddit_id: "t5_2u66g",
								mod_reason_by: null,
								removal_reason: null,
								link_flair_background_color: "",
								id: "ghpx8a",
								is_robot_indexable: true,
								report_reasons: null,
								author: "UFBSuck",
								discussion_type: null,
								num_comments: 0,
								send_replies: true,
								whitelist_status: "all_ads",
								contest_mode: false,
								mod_reports: [],
								author_patreon_flair: false,
								author_flair_text_color: null,
								permalink:
									"/r/UXDesign/comments/ghpx8a/we_have_curated_a_list_of_resources_about_user/",
								parent_whitelist_status: "all_ads",
								stickied: false,
								url:
									"https://www.reddit.com/r/UXDesign/comments/ghpx8a/we_have_curated_a_list_of_resources_about_user/",
								subreddit_subscribers: 40613,
								created_utc: 1589211676,
								num_crossposts: 0,
								media: null,
								is_video: false,
							},
							author: "UFBSuck",
							id: "ghpx8a",
							fullname: "t3_ghpx8a",
							subreddit: "UXDesign",
							subredditID: "t5_2u66g",
							redditLink:
								"/r/UXDesign/comments/ghpx8a/we_have_curated_a_list_of_resources_about_user/",
							title: "We have curated a list of resources about User Flow",
							url:
								"https://www.reddit.com/r/UXDesign/comments/ghpx8a/we_have_curated_a_list_of_resources_about_user/",
							isVideo: false,
							media: null,
							numComment: 0,
							postHint: "self",
							isSelf: true,
							thumbnail: "self",
							type: "text",
							mediaURL: "",
						},
						{
							text: "",
							kind: "t3",
							data: {
								approved_at_utc: null,
								subreddit: "UXDesign",
								selftext: "",
								author_fullname: "t2_a2bpxr8",
								saved: true,
								mod_reason_title: null,
								gilded: 0,
								clicked: false,
								title: "A UX Analysis of Xbox Passkey",
								link_flair_richtext: [],
								subreddit_name_prefixed: "r/UXDesign",
								hidden: false,
								pwls: 6,
								link_flair_css_class: null,
								downs: 0,
								thumbnail_height: 78,
								top_awarded_type: null,
								hide_score: false,
								name: "t3_jri1eh",
								quarantine: false,
								link_flair_text_color: "dark",
								upvote_ratio: 1,
								author_flair_background_color: null,
								subreddit_type: "public",
								ups: 3,
								total_awards_received: 0,
								media_embed: {},
								thumbnail_width: 140,
								author_flair_template_id: null,
								is_original_content: false,
								user_reports: [],
								secure_media: null,
								is_reddit_media_domain: false,
								is_meta: false,
								category: null,
								secure_media_embed: {},
								link_flair_text: null,
								can_mod_post: false,
								score: 3,
								approved_by: null,
								author_premium: false,
								thumbnail:
									"https://b.thumbs.redditmedia.com/Nh76bvN3oij5MNWC5cAKkU2vKPXkSTKUyd3ZlONo2HE.jpg",
								edited: false,
								author_flair_css_class: null,
								author_flair_richtext: [],
								gildings: {},
								post_hint: "link",
								content_categories: null,
								is_self: false,
								mod_note: null,
								created: 1605029388,
								link_flair_type: "text",
								wls: 6,
								removed_by_category: null,
								banned_by: null,
								author_flair_type: "text",
								domain: "medium.com",
								allow_live_comments: false,
								selftext_html: null,
								likes: null,
								suggested_sort: null,
								banned_at_utc: null,
								url_overridden_by_dest:
									"https://medium.com/super-jump/a-ux-analysis-of-xbox-passkey-dedbc871648d",
								view_count: null,
								archived: false,
								no_follow: false,
								is_crosspostable: true,
								pinned: false,
								over_18: false,
								preview: {
									images: [
										{
											source: {
												url:
													"https://external-preview.redd.it/izZxtsWRyhrHhpS9ahnTzYyHv5K_T-2mgiACHm0s1Jw.jpg?auto=webp&amp;s=12722a19f0a3364c333c01611749d7f62a68d3d9",
												width: 1200,
												height: 675,
											},
											resolutions: [
												{
													url:
														"https://external-preview.redd.it/izZxtsWRyhrHhpS9ahnTzYyHv5K_T-2mgiACHm0s1Jw.jpg?width=108&amp;crop=smart&amp;auto=webp&amp;s=277448f0074b7fcb73fc15ee2ccafe5765bffcc9",
													width: 108,
													height: 60,
												},
												{
													url:
														"https://external-preview.redd.it/izZxtsWRyhrHhpS9ahnTzYyHv5K_T-2mgiACHm0s1Jw.jpg?width=216&amp;crop=smart&amp;auto=webp&amp;s=3530513d2677671eb22883be54ed1fbd83333785",
													width: 216,
													height: 121,
												},
												{
													url:
														"https://external-preview.redd.it/izZxtsWRyhrHhpS9ahnTzYyHv5K_T-2mgiACHm0s1Jw.jpg?width=320&amp;crop=smart&amp;auto=webp&amp;s=3aa64ab6435324d25fd1b824f4cda448b0adf1e2",
													width: 320,
													height: 180,
												},
												{
													url:
														"https://external-preview.redd.it/izZxtsWRyhrHhpS9ahnTzYyHv5K_T-2mgiACHm0s1Jw.jpg?width=640&amp;crop=smart&amp;auto=webp&amp;s=99608f98a40ab76f8396a99896adb3e8045646fe",
													width: 640,
													height: 360,
												},
												{
													url:
														"https://external-preview.redd.it/izZxtsWRyhrHhpS9ahnTzYyHv5K_T-2mgiACHm0s1Jw.jpg?width=960&amp;crop=smart&amp;auto=webp&amp;s=08c2fcc7b0d273ac523f306cc5688f1446f0889d",
													width: 960,
													height: 540,
												},
												{
													url:
														"https://external-preview.redd.it/izZxtsWRyhrHhpS9ahnTzYyHv5K_T-2mgiACHm0s1Jw.jpg?width=1080&amp;crop=smart&amp;auto=webp&amp;s=0f260973e8f9321c59bcef146a99f52327973d7a",
													width: 1080,
													height: 607,
												},
											],
											variants: {},
											id: "o-JSiZH5hOOtWnCgHFb45Vt-TxiJhM2myWMi_GEcRfA",
										},
									],
									enabled: false,
								},
								all_awardings: [],
								awarders: [],
								media_only: false,
								can_gild: true,
								spoiler: false,
								locked: false,
								author_flair_text: null,
								treatment_tags: [],
								visited: false,
								removed_by: null,
								num_reports: null,
								distinguished: null,
								subreddit_id: "t5_2u66g",
								mod_reason_by: null,
								removal_reason: null,
								link_flair_background_color: "",
								id: "jri1eh",
								is_robot_indexable: true,
								report_reasons: null,
								author: "bogdanelcs",
								discussion_type: null,
								num_comments: 2,
								send_replies: false,
								whitelist_status: "all_ads",
								contest_mode: false,
								mod_reports: [],
								author_patreon_flair: false,
								author_flair_text_color: null,
								permalink:
									"/r/UXDesign/comments/jri1eh/a_ux_analysis_of_xbox_passkey/",
								parent_whitelist_status: "all_ads",
								stickied: false,
								url:
									"https://medium.com/super-jump/a-ux-analysis-of-xbox-passkey-dedbc871648d",
								subreddit_subscribers: 40613,
								created_utc: 1605000588,
								num_crossposts: 0,
								media: null,
								is_video: false,
							},
							author: "bogdanelcs",
							id: "jri1eh",
							fullname: "t3_jri1eh",
							subreddit: "UXDesign",
							subredditID: "t5_2u66g",
							redditLink:
								"/r/UXDesign/comments/jri1eh/a_ux_analysis_of_xbox_passkey/",
							title: "A UX Analysis of Xbox Passkey",
							url:
								"https://medium.com/super-jump/a-ux-analysis-of-xbox-passkey-dedbc871648d",
							isVideo: false,
							media: null,
							numComment: 2,
							postHint: "link",
							isSelf: false,
							thumbnail:
								"https://b.thumbs.redditmedia.com/Nh76bvN3oij5MNWC5cAKkU2vKPXkSTKUyd3ZlONo2HE.jpg",
							urlOverriddenByDest:
								"https://medium.com/super-jump/a-ux-analysis-of-xbox-passkey-dedbc871648d",
							type: "link",
							mediaURL: "",
						},
					],
				},
			})

			.persist();
	});

	test("Input text", () => {
		const wrapper = getWrapper();
		expect(wrapper.exists()).toBeTruthy();
		/*	const wrapper = getWrapper();
		console.log("Phase 1 ");
		await flushPromises();
		await waitUntil(() => {
			console.log("START");
			console.log(wrapper.attributes("items"));
			return wrapper.attributes("items").length > 0;
		}, 10000)
			.then(() => {
				console.log("Phase 3");
				expect(wrapper.exists()).toBeTruthy();
				console.log("Phase 4 ");
				return null;
			})
			// eslint-disable-next-line promise/no-callback-in-promise
			.catch((err) => {
				console.log("ERROR");
				console.log(err);
				return null;
			});
		console.log("Phase 2 ");
		// await flushPromises();
		*/
	});

	test("Baddly formed url", () => {});

	test("Well formed  but invalid url", () => {});

	test("Well formed  & valid url", () => {});
});
